### ISSUE TITLE
Не запускается в Linux

### ISSUE THREAD

**Issue by xupyprmv** [xupyprmv/arismorf#1]
[MysqldResource] launching mysqld (getOptions)
[./db/arismorf/bin/mysqld][--no-defaults][--port=3307][--socket=./db/arismorf/mysql.sock][--basedir=./db/arismorf][--datadir=./db/arismorf/data][--pid-file=./db/arismorf/MysqldResource.pid]
[MysqldResource] launching mysqld (arismorf)
110912 12:27:15 [ERROR] Can't start server : Bind on unix socket: No such file or directory
110912 12:27:15 [ERROR] Do you already have another mysqld server running on socket: ./db/arismorf/mysql.sock ?
110912 12:27:15 [ERROR] Aborting

110912 12:27:15 [Note] ./db/arismorf/bin/mysqld: Shutdown complete

Возможно следующее:
mysql.sock создаётся не в той папке где ожидается

**Comment by derak29** [comment]
Hello anybody can explain please how i can fix this issue?


Running org.jboss.aerogear.unifiedpush.migrator.MigratorTest
[/tmp/unifiedpush/bin/mysqld][--no-defaults][--basedir=/tmp/unifiedpush][--socket=mysql.sock][--port=35767][--datadir=/tmp/unifiedpush/data][--pid-file=/tmp/unifiedpush/data/MysqldResource.pid]
[MysqldResource] launching mysqld (mysql)
170727  8:48:13 [ERROR] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!

170727  8:48:13 [ERROR] Aborting

170727  8:48:13 [Note] /tmp/unifiedpush/bin/mysqld: Shutdown complete

[MysqldResource] 
[MysqldResource] mysqld pid-file not found:  /tmp/unifiedpush/data/MysqldResource.pid
[MysqldResource] Mysqld not running. No file: /tmp/unifiedpush/data/MysqldResource.pid
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 425.803 sec <<< FAILURE!
shouldCreateDatabaseFromScratch(org.jboss.aerogear.unifiedpush.migrator.MigratorTest)  Time elapsed: 425.647 sec  <<< ERROR!
liquibase.exception.DatabaseException: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at com.mysql.jdbc.StandardSocketFactory.connect(StandardSocketFactory.java:257)
	at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:294)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2332)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2369)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2153)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:792)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.GeneratedConstructorAccessor2.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:381)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
	at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:231)
	at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:143)
	at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:132)
	at org.jboss.aerogear.unifiedpush.migrator.MigratorTest.initDatabase(MigratorTest.java:65)
	at org.jboss.aerogear.unifiedpush.migrator.MigratorTest.init(MigratorTest.java:41)


Results :

Tests in error: 
  MigratorTest.init:41->initDatabase:65 ? Database com.mysql.jdbc.exceptions.jdb...

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] AeroGear UnifiedPush Server ........................ SUCCESS [ 29.041 s]
[INFO] UnifiedPush Model Layer ............................ SUCCESS [  0.110 s]
[INFO] UnifiedPush Server Model API ....................... SUCCESS [  9.542 s]
[INFO] UnifiedPush Common classes and utils ............... SUCCESS [  1.884 s]
[INFO] UnifiedPush Server Model JPA implementation ........ SUCCESS [ 37.597 s]
[INFO] UnifiedPush Database Migrator ...................... FAILURE [07:24 min]
[INFO] UnifiedPush Service Layer .......................... SKIPPED
[INFO] UnifiedPush Sender Module .......................... SKIPPED
[INFO] UnifiedPush Push Message Model ..................... SKIPPED
[INFO] UnifiedPush Push Notification Networks ............. SKIPPED
[INFO] UnifiedPush RESTful Endpoint ....................... SKIPPED
[INFO] UnifiedPush Admin UI ............................... SKIPPED
[INFO] UnifiedPush Dependencies Parent .................... SKIPPED
[INFO] UnifiedPush Server Dependencies Server ............. SKIPPED
[INFO] UnifiedPush Auth Server ............................ SKIPPED
[INFO] UnifiedPush Server for Wildfly (WAR) ............... SKIPPED
[INFO] UnifiedPush Servers Parent ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 08:49 min
[INFO] Finished at: 2017-07-27T08:55:17-04:00
[INFO] Final Memory: 67M/162M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.14.1:test (default-test) on project unifiedpush-migrator: There are test failures.
[ERROR] 
[ERROR] Please refer to /root/aerogear-unifiedpush-server/migrator/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :unifiedpush-migrator

**Comment by xupyprmv** [comment]
@derak29 Sorry, your log is not related to project. You can try to ask your question at https://stackoverflow.com/
